[package]
authors = ["Ballerina"]
distribution = "2201.12.6"
keywords = ["Agent", "Model", "Provider", "Vendor/OpenRouter", "Area/AI & Machine Learning", "Type/Embedding Provider", "Type/Model Provider", "Type/Connector", "Name/OpenRouter Model/Embedding Provider"]
license = ["Apache-2.0"]
name = "ai.openrouter"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.openrouter"
version = "1.0.0"
icon="icon.png"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.openrouter-native"
version = "1.0.0"
path = "../native/build/libs/ai.openrouter-native-1.0.0-SNAPSHOT.jar"
