[plugin]
id = "ai-openrouter-compiler-plugin"
class = "io.ballerina.lib.ai.openrouter.compiler.AiOpenRouterCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/ai.openrouter-compiler-plugin-1.0.0-SNAPSHOT.jar"

[[dependency]]
path = "../compiler-plugin/build/libs/ballerina-to-openapi-2.3.0.jar"
