// Copyright (c) 2025 WSO2 LLC (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/ai;
import ballerina/ai.observe;
import ballerina/http;
import ballerina/jballerina.java;
import ballerinax/openai.chat;

const DEFAULT_OPENROUTER_SERVICE_URL = "https://openrouter.ai/api/v1";
const DEFAULT_CHAT_COMPLETION_PATH = "/chat/completions";
const DEFAULT_MAX_TOKEN_COUNT = 512;
const DEFAULT_TEMPERATURE = 0.7d;

# ModelProvider is a client class that provides an interface for interacting with
# LLMs via the OpenRouter unified API, which supports models from OpenAI, Anthropic,
# Google, Meta, Mistral, and many other providers.
public isolated distinct client class ModelProvider {
    *ai:ModelProvider;
    private final http:Client httpClient;
    private final OPENROUTER_MODEL_NAMES modelType;
    private final decimal temperature;
    private final int maxTokens;
    private final map<string|string[]> & readonly requestHeaders;

    # Initializes the OpenRouter model provider with the given configuration.
    #
    # + apiKey - The OpenRouter API key (obtain from https://openrouter.ai/keys)
    # + modelType - The OpenRouter model to use (e.g., `openai/gpt-4o`, `anthropic/claude-3.5-sonnet`)
    # + serviceUrl - The base URL of the OpenRouter API endpoint
    # + siteUrl - Optional site URL sent as `HTTP-Referer` header for OpenRouter attribution
    # + siteName - Optional site name sent as `X-Title` header for OpenRouter attribution
    # + maxTokens - The upper limit for the number of tokens in the response generated by the model
    # + temperature - The temperature for controlling randomness in the model's output
    # + connectionConfig - Additional HTTP connection configuration
    # + return - `()` on successful initialization; otherwise, returns an `ai:Error`
    public isolated function init(@display {label: "API Key"} string apiKey,
            @display {label: "Model Type"} OPENROUTER_MODEL_NAMES modelType,
            @display {label: "Service URL"} string serviceUrl = DEFAULT_OPENROUTER_SERVICE_URL,
            @display {label: "Site URL"} string? siteUrl = (),
            @display {label: "Site Name"} string? siteName = (),
            @display {label: "Maximum Tokens"} int maxTokens = DEFAULT_MAX_TOKEN_COUNT,
            @display {label: "Temperature"} decimal temperature = DEFAULT_TEMPERATURE,
            @display {label: "Connection Configuration"} *ConnectionConfig connectionConfig) returns ai:Error? {
        http:ClientHttp1Settings http1Settings = connectionConfig.http1Settings ?: {};
        http:ClientHttp2Settings http2Settings = connectionConfig.http2Settings ?: {};
        http:CacheConfig cache = connectionConfig.cache ?: {};
        http:ResponseLimitConfigs responseLimits = connectionConfig.responseLimits ?: {};

        http:ClientConfiguration httpConfig = {
            auth: {token: apiKey},
            httpVersion: connectionConfig.httpVersion,
            http1Settings: http1Settings,
            http2Settings: http2Settings,
            timeout: connectionConfig.timeout,
            forwarded: connectionConfig.forwarded,
            poolConfig: connectionConfig.poolConfig,
            cache: cache,
            compression: connectionConfig.compression,
            circuitBreaker: connectionConfig.circuitBreaker,
            retryConfig: connectionConfig.retryConfig,
            responseLimits: responseLimits,
            secureSocket: connectionConfig.secureSocket,
            proxy: connectionConfig.proxy,
            validation: connectionConfig.validation
        };

        http:Client|error httpClient = new (serviceUrl, httpConfig);
        if httpClient is error {
            return error ai:Error("Failed to initialize OpenRouterProvider", httpClient);
        }
        self.httpClient = httpClient;
        self.modelType = modelType;
        self.temperature = temperature;
        self.maxTokens = maxTokens;

        // Pre-build optional OpenRouter attribution headers
        map<string|string[]> headers = {};
        if siteUrl is string {
            headers["HTTP-Referer"] = siteUrl;
        }
        if siteName is string {
            headers["X-Title"] = siteName;
        }
        self.requestHeaders = headers.cloneReadOnly();
    }

    # Sends a chat request to the OpenRouter model with the given messages and tools.
    #
    # + messages - List of chat messages or a single user message
    # + tools - Tool definitions to be used for the tool call
    # + stop - Stop sequence to stop the completion
    # + return - Function to be called, chat response or an error in-case of failures
    isolated remote function chat(ai:ChatMessage[]|ai:ChatUserMessage messages, ai:ChatCompletionFunctions[] tools = [],
            string? stop = ()) returns ai:ChatAssistantMessage|ai:Error {
        observe:ChatSpan span = observe:createChatSpan(self.modelType);
        span.addProvider("openrouter");
        if stop is string {
            span.addStopSequence(stop);
        }
        span.addTemperature(self.temperature);
        json|ai:Error inputMessage = convertMessageToJson(messages);
        if inputMessage is json {
            span.addInputMessages(inputMessage);
        }

        chat:CreateChatCompletionRequest request = {
            max_completion_tokens: self.maxTokens,
            temperature: self.temperature,
            stop,
            model: self.modelType,
            messages: check self.prepareCompletionRequestMessages(messages, tools)
        };
        if tools.length() > 0 {
            request.functions = tools;
            span.addTools(tools);
        }

        chat:CreateChatCompletionResponse|error response = self.httpClient->post(
            DEFAULT_CHAT_COMPLETION_PATH, request, self.requestHeaders);
        if response is error {
            ai:Error err = error ai:LlmConnectionError("Error while connecting to the model", response);
            span.close(err);
            return err;
        }
        chat:CreateChatCompletionResponse_choices[] choices = response.choices;
        if choices.length() == 0 {
            ai:Error err = error ai:LlmInvalidResponseError("Empty response from the model when using function call API");
            span.close(err);
            return err;
        }

        span.addResponseId(response.id);
        int? inputTokens = response.usage?.prompt_tokens;
        if inputTokens is int {
            span.addInputTokenCount(inputTokens);
        }
        int? outputTokens = response.usage?.completion_tokens;
        if outputTokens is int {
            span.addOutputTokenCount(outputTokens);
        }
        string? finishReason = response.choices[0].finish_reason;
        if finishReason is string {
            span.addFinishReason(finishReason);
        }

        ai:ChatAssistantMessage|ai:Error message = self.convertResponseToAssistantMessage(choices[0].message);
        if message is ai:Error {
            span.close(message);
            return message;
        }
        span.addOutputMessages(message);
        span.addOutputType(observe:TEXT);
        span.close();
        return message;
    }

    # Sends a chat request to the model and generates a value of the type specified by
    # the `td` type descriptor. For complex record types, annotate the type with
    # `@ai:JsonSchema` to enable compile-time schema generation.
    #
    # + prompt - The prompt to use in the chat messages
    # + td - Type descriptor specifying the expected return type format
    # + return - Generates a value that belongs to the type, or an error if generation fails
    isolated remote function generate(ai:Prompt prompt,
            @display {label: "Expected type"} typedesc<anydata> td = <>) returns td|ai:Error = @java:Method {
        'class: "io.ballerina.lib.ai.openrouter.Generator"
    } external;

    private isolated function prepareCompletionRequestMessages(ai:ChatMessage[]|ai:ChatUserMessage messages,
            ai:ChatCompletionFunctions[] tools) returns chat:ChatCompletionRequestMessage[]|ai:Error {
        chat:ChatCompletionRequestMessage[] chatCompletionRequestMessages = [];
        if messages is ai:ChatUserMessage {
            chatCompletionRequestMessages.push({
                role: ai:USER,
                content: check getChatMessageStringContent(messages.content),
                name: messages.name
            });
            return chatCompletionRequestMessages;
        }
        foreach ai:ChatMessage message in messages {
            if message is ai:ChatAssistantMessage {
                chat:ChatCompletionRequestAssistantMessage assistantMessage = self.buildRequestAssistantMessage(message);
                chatCompletionRequestMessages.push(assistantMessage);
            } else if message is ai:ChatUserMessage {
                chatCompletionRequestMessages.push({
                    role: ai:USER,
                    content: check getChatMessageStringContent(message.content),
                    name: message.name
                });
            } else if message is ai:ChatSystemMessage {
                chatCompletionRequestMessages.push({
                    role: ai:SYSTEM,
                    content: check getChatMessageStringContent(message.content),
                    name: message.name
                });
            } else if message is ai:ChatFunctionMessage|ai:ChatAssistantMessage {
                chatCompletionRequestMessages.push(message);
            }
        }
        return chatCompletionRequestMessages;
    }

    private isolated function buildRequestAssistantMessage(ai:ChatAssistantMessage message)
    returns chat:ChatCompletionRequestAssistantMessage {
        chat:ChatCompletionRequestAssistantMessage assistantMessage = {role: ai:ASSISTANT};
        ai:FunctionCall[]? toolCalls = message.toolCalls;
        if toolCalls is ai:FunctionCall[] {
            ai:FunctionCall functionCall = toolCalls[0];
            assistantMessage.function_call = {
                name: functionCall.name,
                arguments: functionCall.arguments.toJsonString()
            };
        }
        string? content = message?.content;
        if content is string {
            assistantMessage.content = content;
        }
        return assistantMessage;
    }

    private isolated function convertResponseToAssistantMessage(chat:ChatCompletionResponseMessage? message)
    returns ai:ChatAssistantMessage|ai:LlmError {
        do {
            ai:ChatAssistantMessage chatAssistantMessage = {role: ai:ASSISTANT};
            chatAssistantMessage.content = message?.content;
            chat:ChatCompletionRequestAssistantMessage_function_call? functionCall = message?.function_call;
            if functionCall is chat:ChatCompletionRequestAssistantMessage_function_call {
                json arguments = check functionCall.arguments.fromJsonString();
                chatAssistantMessage.toolCalls = [
                    {
                        name: functionCall.name,
                        arguments: check arguments.cloneWithType()
                    }
                ];
            }
            return chatAssistantMessage;
        } on fail error e {
            return error("Invalid or malformed arguments received in function call response.", e);
        }
    }
}
